CREATE TABLE ACCOUNT(
Accno INT(15) NOT NULL PRIMARY KEY,
Name VARCHAR(25) NOT NULL,
Age INT(5) NOT NULL,
Occu VARCHAR(15) NOT NULL,
Address VARCHAR(50) NOT NULL,
Mob BIGINT NOT NULL,
Aadharno BIGINT,
amt DOUBLE(20,5),
AccType VARCHAR(15) NOT NULL );

CREATE TABLE amt(
Accno INT(15),
Amtdeposit DOUBLE(20,5),
month VARCHAR(15) NOT NULL );